'use client';
import {useEffect,useRef,useState} from 'react';
import {sessionFetch, clearSession} from './session-client.mjs';
import VoiceControls from './components/VoiceControls';
import Report from './components/Report';
import Review from './components/Review';
import AnswerChoices from './components/AnswerChoices';
import SessionNotice from './components/SessionNotice';
function Mark(){return <span className="mark" aria-hidden="true">a<span>✦</span></span>}
function Botanical(){return <svg className="botanical" viewBox="0 0 300 330" fill="none" aria-hidden="true"><path d="M152 305C150 235 189 174 154 62M155 235C110 213 86 171 82 126M165 178C214 151 236 125 238 78" stroke="currentColor" strokeWidth="2"/>{[[146,80,-20],[168,121,30],[141,171,-35],[119,208,-50],[192,158,40],[224,115,35],[85,140,-30],[165,257,25]].map(([x,y,r],i)=><ellipse key={i} cx={x} cy={y} rx="17" ry="36" transform={`rotate(${r} ${x} ${y})`} fill="currentColor" opacity={.35+i*.06}/>)}<circle cx="65" cy="64" r="27" fill="#e3bd75" opacity=".65"/></svg>}
async function api(path,method='GET',body){
 const r=await sessionFetch(path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
 const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'The request could not be completed. Review your input and try again.');return data;
}
export default function Home(){
 const [health,setHealth]=useState(null),[session,setSession]=useState(null),[view,setView]=useState('interview'),[report,setReport]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState(''),[original,setOriginal]=useState(''),[help,setHelp]=useState(false),[context,setContext]=useState({onset:'',impact:'',routines:'',interests:'',other_observations:''});
 const [reviewQuestion,setReviewQuestion]=useState(null);
 const questionHeading=useRef(null);
 const operation=useRef(false),lastQuestion=useRef(null),retryRequest=useRef(null);
 useEffect(()=>{window.scrollTo({top:0})},[view,session?.id]);
 useEffect(()=>{api('/health').then(setHealth).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!session)return;const key=session.id+':'+session.current_question.id;if(lastQuestion.current!==key){setText('');setOriginal('');setHelp(false);lastQuestion.current=key}},[session?.id,session?.current_question.id]);
 useEffect(()=>{if(view==='interview'&&session?.status==='running')questionHeading.current?.focus()},[view,session?.current_question.id,session?.status]);
 function review(qid=null){setReviewQuestion(qid);setView('review')}
 function expire(){clearSession();setSession(null);setReport(null);setText('');setOriginal('');setContext({onset:'',impact:'',routines:'',interests:'',other_observations:''});setError('This temporary session has expired. Its interview and reports are no longer available. You can start a new conversation below.')}
 async function run(fn){if(operation.current)return;operation.current=true;setBusy(true);setError('');try{await fn();return true}catch(e){setSession(previous=>previous?.report_status==='generating'?{...previous,report_status:'failed',report_error:'The report could not finish. Your responses are still here; please retry.'}:previous);setError(e.message);return false}finally{operation.current=false;setBusy(false)}}
 async function mutate(suffix,body={},method='POST'){
  return await run(async()=>{
   const fingerprint=JSON.stringify([session.id,suffix,body,method,session.revision]);
   if(retryRequest.current?.fingerprint!==fingerprint)retryRequest.current={fingerprint,id:crypto.randomUUID()};
   if(suffix==='/reports')setSession(previous=>({...previous,report_status:'generating',report_started_at:Date.now()/1000}));
   const s=await api(`/sessions/${session.id}${suffix}`,method,{...body,revision:session.revision,request_id:retryRequest.current.id});retryRequest.current=null;setSession(s);if(suffix==='/turns'){setText('');setOriginal('')}return s;
  });
 }
 async function start(e){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const s=await api('/sessions','POST',{name:f.get('name'),age:Number(f.get('age')),relationship:f.get('relationship')||'Caregiver',observation_context:{setting:f.get('setting')||'',frequency:f.get('frequency')||'',familiarity:f.get('familiarity')||''},mode:'interactive',consent:f.get('consent')==='on'});setSession(s);setContext(s.context);setView('interview')})}
 async function resume(sid){await run(async()=>{const s=await api('/sessions/'+sid);setSession(s);setContext(s.context);setView(s.status==='complete'?'review':'interview');setReport(null)})}
 async function openReport(id){await run(async()=>{const r=await api(`/sessions/${session.id}/reports/${id}`);setReport(r);setView('report')})}
 async function remove(){if(!window.confirm('End this session and clear its interview and reports? Download your report first.'))return;await run(async()=>{await api(`/sessions/${session.id}`,'DELETE');clearSession();setSession(null);setReport(null);setView('interview')})}
 const answered=session?Object.keys(session.answers).length:0;
 return <div className="site haven"><div className="app-shell"><header className="header"><button className="brand" onClick={()=>{if(session){remove()}else{setView('interview')}}} aria-label="ASDWise home"><Mark/> ASD<span>wise</span></button><nav aria-label="Application"><button className={view==='interview'?'active':''} onClick={()=>setView('interview')}>Your screening</button><button disabled={!session} className={view!=='interview'?'active':''} onClick={()=>{review()}}>Review & report</button></nav><span className="pilot-tag">Caregiver screening</span></header><div className="workspace"><aside className="sidebar"><div className="eyebrow">YOUR JOURNEY</div><h2>A little understanding.<br/>A meaningful next step.</h2><p>Your everyday observations matter. Let’s start with the moments you know.</p><div className="steps"><div className={`step ${!session?'now':'done'}`}><span>{session?'✓':'01'}</span><div>Before you begin<small>A little context</small></div></div><button className={`step ${session&&view==='interview'?'now':''}`} disabled={!session} onClick={()=>setView('interview')}><span>02</span><div>Sharing your observations<small>{answered} of 20 responses recorded</small></div></button><button className={`step ${session&&view!=='interview'?'now':''}`} disabled={!session} onClick={()=>{review()}}><span>03</span><div>Your report<small>Evidence and next steps</small></div></button></div><Botanical/><div className="side-footer">Thoughtfully guided.<br/>Grounded in your observations.</div></aside><main>
 {error&&<div className="notice error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button>{session&&<button onClick={()=>resume(session.id)}>Refresh session</button>}</div>}
 {!session?<><div className="page-heading"><div><div className="eyebrow">WELCOME TO ASDWISE</div><h1>Let’s talk about the child you care for.</h1><p>A guided conversation about communication, play, and everyday life.</p></div><span className="age-tag">16–30 months</span></div><div className="content-grid"><form className="question-card onboarding" onSubmit={start}><h2>Start with a little context.</h2><p>The AI screening guide helps you record observations. A qualified professional makes diagnostic decisions.</p><p>This questionnaire is intended for children aged 16–30 months. If your child is outside this range, ask their healthcare professional about an age-appropriate developmental screening.</p>
 <div className="start-overview"><strong>20 questions → Review your answers → Download your report</strong><p>Answer with a short selection or an everyday example. A nickname is enough; no account is needed.</p><p><strong>Plan to finish in this tab.</strong> Closing or refreshing loses access to your progress. Pausing does not stop the 30-minute inactivity limit.</p></div><label>Child’s preferred name<input name="name" maxLength={80} required placeholder="First name or nickname"/></label><div className="form-row"><label>Age in months<input name="age" type="number" min="16" max="30" required placeholder="16–30"/></label><label>Your relationship<input name="relationship" required maxLength={60} defaultValue="Parent"/></label></div>
 <fieldset className="observation-setup"><legend>Your observation context (optional)</legend><p>Answer from your own experience. It’s okay if you do not see every setting.</p><label>Where do you usually observe the child?<input name="setting" maxLength={200} placeholder="For example: home, daycare, quiet one-to-one play"/></label><label>How often and at what times?<input name="frequency" maxLength={200} placeholder="For example: weekdays, evenings, weekends"/></label><label>How long have you cared for the child?<input name="familiarity" maxLength={200} placeholder="For example: since birth, or eight weeks"/></label></fieldset>
 {health&&!health.live_available&&<div className="notice" role="status">Conversations are temporarily unavailable. Please try again later. Please keep this page open if you have an interview in progress.</div>}
 <div className="privacy-summary"><h3>Before you share</h3><ul><li>Your interview and any recorded audio are sent to OpenAI, which processes them under its own data policies.</li><li>This app keeps your interview in this browser tab’s memory and sends it with each request; it does not save it in a database. Raw recordings are not saved by this app.</li><li>The session clears when you end it, after 30 minutes without updates, or when you close or refresh this tab. Download your report before leaving.</li></ul></div><label className="consent"><input type="checkbox" name="consent" required/><span>I understand this is a screening tool, not a diagnosis, and agree to the processing described above.</span></label><button className="primary" disabled={busy||!health?.live_available}>{busy?'Starting…':'Start conversation →'}</button>
 </form><aside className="support"><div className="support-art"><Botanical/></div><div className="eyebrow">A NOTE FOR YOU</div><h3>There’s no perfect answer.</h3><p>Think about what usually happens. You can describe an example, say you’re unsure, or take a short break with this tab open.</p><hr/><h4>Your words matter.</h4><p>Review every answer before it contributes to a screening report.</p></aside></div></>
 :<>
 <SessionNotice session={session} busy={busy} onKeepOpen={()=>mutate('/control',{action:'keepalive'})} onExpired={expire}/>
 {view==='report'&&report?<Report report={report} session={session} onBack={()=>review()}/>:view==='review'?<Review key={reviewQuestion??'all'} session={session} busy={busy} context={context} setContext={setContext} mutate={mutate} onReturn={()=>setView('interview')} onOpenReport={openReport} focusQuestion={reviewQuestion}/>:<><div className="page-heading"><div><div className="eyebrow">{session.child.name.toUpperCase()}’S INTERVIEW</div><h1>One question at a time.</h1><p>Share what you’ve noticed, in your own words.</p></div><span className="age-tag">{session.child.age} months</span></div><div className="session-controls">{session.current_question.id>1&&<button className="secondary" disabled={busy} onClick={()=>review(session.current_question.id-1)}>← Review previous answer</button>}<button className="secondary" disabled={busy||session.status==='complete'} onClick={()=>{mutate('/control',{action:session.status==='running'?'pause':'resume'})}}>{session.status==='running'?'Pause interview':'Resume interview'}</button><button className="quiet" disabled={busy} onClick={()=>{if(window.confirm('Reset this interview? Existing reports will remain as earlier versions.')){setContext({onset:'',impact:'',routines:'',interests:'',other_observations:''});mutate('/control',{action:'reset'})}}}>Reset</button></div>
 {session.status==='complete'?<div className="question-card"><h2>Thank you for sharing.</h2><p>All 20 questions have a recorded response. Review anything you were unsure about before generating your report.</p><button className="primary" onClick={()=>{review()}}>Review responses →</button></div>:<section className="question-card conversation-card"><div className="question-meta"><span>QUESTION {String(session.current_question.id).padStart(2,'0')} / 20</span><span>{session.status==='running'?'In progress':session.status}</span></div><div className="progress" role="progressbar" aria-label="Screening progress" aria-valuenow={answered} aria-valuemin={0} aria-valuemax={20}><i style={{width:`${answered*5}%`}}/></div><div className="guide-heading"><Mark/><span>ASDwise AI screening guide<small>Your observations guide the screening</small></span></div><h2 ref={questionHeading} tabIndex={-1}>{session.current_question.text}</h2>
 <div className="transcript" aria-live="polite">{session.turns.filter(t=>t.question_id===session.current_question.id&&t.text!==session.current_question.text).map(t=><div key={t.id} className={`message ${t.role}`}><small>{t.role==='caregiver'?'Caregiver':'AI guide'}</small><p>{t.text}</p></div>)}</div>
 {session.status!=='running'?<div className="notice"><strong>Your interview is paused.</strong><p>Keep this tab open. Pausing does not stop the 30-minute inactivity limit. Closing or refreshing loses access to your progress.</p><button className="primary" disabled={busy} onClick={()=>mutate('/control',{action:'resume'})}>Resume interview →</button></div>:<>
 <button className="help-link" aria-expanded={help} aria-controls="question-help" onClick={()=>setHelp(!help)}>Help me understand</button>
 {help&&<div className="notice" id="question-help"><strong>You don’t have to guess.</strong><p>Think about what usually happens across several recent situations. You can ask the guide to clarify the wording in the box below. If you’re still unsure, choose “Not sure” and continue.</p></div>}
 <form className="response-form" onSubmit={e=>{e.preventDefault();mutate('/turns',{text,modality:original?'voice':'text',original_transcript:original})}}><label htmlFor="response">{session.pending?'Answer the guide or ask another question (optional)':'Add an example or ask the guide (optional)'}<textarea id="response" maxLength={6000} value={text} onChange={e=>setText(e.target.value)} placeholder="Describe what you’ve noticed, or ask what the question means…" disabled={busy}/></label>{original&&<p className="muted-copy">Voice transcript ready. Check the wording before sending.</p>}<div className="question-footer"><span>Want help? Send your example first, then confirm your answer below.</span><button className="secondary" disabled={busy||!text.trim()}>{busy?'Guide is responding…':'Send to guide'}</button>{text&&<button type="button" className="quiet" disabled={busy} onClick={()=>{setText('');setOriginal('')}}>Clear draft</button>}</div></form>
 <VoiceControls session={session} enabled={health?.audio_available} disabled={busy} onTranscript={v=>{setOriginal(v);setText(v)}} onError={setError}/>
 <AnswerChoices key={session.current_question.id} question={session.current_question} busy={busy} pending={!!session.pending} hasDraft={!!text.trim()} onConfirm={value=>mutate(`/answers/${session.current_question.id}`,{value},'PATCH')}/>
 </>}

 </section>}
 <details className="history"><summary>Full interview transcript ({session.turns.filter(t=>t.role!=='superseded').length} messages)</summary>{session.turns.filter(t=>t.role!=='superseded').map(t=><div key={t.id} className={`message ${t.role}`}><small>{t.role==='caregiver'?'Caregiver':'AI guide'}{t.question_id?` · Q${t.question_id}`:''}</small><p>{t.text}</p></div>)}</details></>}
 <div className="session-bottom"><small>Temporary session · No account or saved history · Download your report before leaving</small><button className="danger-link" disabled={busy} onClick={remove}>End session & clear data</button></div></>}
 </main></div><footer className="app-footer"><span>ASDwise · Caregiver-centered understanding</span><span>Screening is not diagnosis</span></footer></div></div>
}
