'use client';
import {useEffect,useRef,useState} from 'react';
import VoiceControls from './components/VoiceControls';
import Report from './components/Report';
function Mark(){return <span className="mark" aria-hidden="true">a<span>✦</span></span>}
function Botanical(){return <svg className="botanical" viewBox="0 0 300 330" fill="none" aria-hidden="true"><path d="M152 305C150 235 189 174 154 62M155 235C110 213 86 171 82 126M165 178C214 151 236 125 238 78" stroke="currentColor" strokeWidth="2"/>{[[146,80,-20],[168,121,30],[141,171,-35],[119,208,-50],[192,158,40],[224,115,35],[85,140,-30],[165,257,25]].map(([x,y,r],i)=><ellipse key={i} cx={x} cy={y} rx="17" ry="36" transform={`rotate(${r} ${x} ${y})`} fill="currentColor" opacity={.35+i*.06}/>)}<circle cx="65" cy="64" r="27" fill="#e3bd75" opacity=".65"/></svg>}
async function api(path,method='GET',body){
 const r=await fetch('/api'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
 const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'The request could not be completed. Review your input and try again.');return data;
}
export default function Home(){
 const [health,setHealth]=useState(null),[saved,setSaved]=useState([]),[session,setSession]=useState(null),[view,setView]=useState('interview'),[report,setReport]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[auto,setAuto]=useState(false),[text,setText]=useState(''),[original,setOriginal]=useState(''),[mode,setMode]=useState('interactive'),[help,setHelp]=useState(false),[context,setContext]=useState({onset:'',impact:'',routines:'',interests:''});
 const operation=useRef(false),lastQuestion=useRef(null),retryRequest=useRef(null);
 useEffect(()=>{window.scrollTo({top:0})},[view,session?.id]);
 useEffect(()=>{Promise.all([api('/health'),api('/sessions')]).then(([h,s])=>{setHealth(h);setSaved(s);if(!h.live_available)setMode('simulation')}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!session)return;const key=session.id+':'+session.current_question.id;if(lastQuestion.current!==key){setText('');setOriginal('');setHelp(false);lastQuestion.current=key}},[session?.id,session?.current_question.id]);
 useEffect(()=>{if(!session)return;let active=true;const events=new EventSource(`/api/sessions/${session.id}/events`);events.onmessage=e=>{if(!active)return;const s=JSON.parse(e.data);setSession(previous=>previous?.id===s.id&&previous.revision>s.revision?previous:s)};return()=>{active=false;events.close()}},[session?.id]);
 useEffect(()=>{if(!auto||!session||session.status!=='running'||busy)return;const timer=setTimeout(()=>mutate('/control',{action:'step'}),900);return()=>clearTimeout(timer)},[auto,session?.revision,session?.status,busy]);
 async function run(fn){if(operation.current)return;operation.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message);setAuto(false)}finally{operation.current=false;setBusy(false)}}
 async function mutate(suffix,body={},method='POST'){
  await run(async()=>{
   const fingerprint=JSON.stringify([session.id,suffix,body,method,session.revision]);
   if(retryRequest.current?.fingerprint!==fingerprint)retryRequest.current={fingerprint,id:crypto.randomUUID()};
   const s=await api(`/sessions/${session.id}${suffix}`,method,{...body,revision:session.revision,request_id:retryRequest.current.id});retryRequest.current=null;setSession(s);if(suffix==='/turns'){setText('');setOriginal('')}return s;
  });
 }
 async function start(e){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const s=await api('/sessions','POST',{name:f.get('name')||'Demo child',age:Number(f.get('age')||24),relationship:f.get('relationship')||'Caregiver',mode,profile:f.get('profile')||'moderate_likelihood',consent:f.get('consent')==='on'});setSession(s);setContext(s.context);setView('interview')})}
 async function resume(sid){await run(async()=>{const s=await api('/sessions/'+sid);setSession(s);setContext(s.context);setView(s.status==='complete'?'review':'interview');setReport(null)})}
 async function openReport(id){await run(async()=>{const r=await api(`/sessions/${session.id}/reports/${id}`);setReport(r);setView('report')})}
 async function remove(){if(!window.confirm('Delete this interview and all of its reports from this local pilot?'))return;setAuto(false);await run(async()=>{await api(`/sessions/${session.id}`,'DELETE');setSession(null);setReport(null);setSaved(await api('/sessions'));setView('interview')})}
 const answered=session?Object.keys(session.answers).length:0;
 return <div className="site haven"><div className="app-shell"><header className="header"><button className="brand" onClick={()=>{setAuto(false);setSession(null);setReport(null);api('/sessions').then(setSaved).catch(e=>setError(e.message))}} aria-label="ASDWise home"><Mark/> ASD<span>wise</span></button><nav aria-label="Application"><button className={view==='interview'?'active':''} onClick={()=>setView('interview')}>Your screening</button><button disabled={!session} className={view!=='interview'?'active':''} onClick={()=>{setAuto(false);setView('review')}}>Review & report</button></nav><span className="pilot-tag">Local research pilot</span></header><div className="workspace"><aside className="sidebar"><div className="eyebrow">YOUR JOURNEY</div><h2>A little understanding.<br/>A meaningful next step.</h2><p>You know your child best. Let’s start with the everyday moments.</p><div className="steps"><div className={`step ${!session?'now':'done'}`}><span>{session?'✓':'01'}</span><div>Before you begin<small>A little about your child</small></div></div><button className={`step ${session&&view==='interview'?'now':''}`} disabled={!session} onClick={()=>setView('interview')}><span>02</span><div>Getting to know your child<small>{answered} of 20 responses recorded</small></div></button><button className={`step ${session&&view!=='interview'?'now':''}`} disabled={!session} onClick={()=>{setAuto(false);setView('review')}}><span>03</span><div>Your report<small>Evidence and next steps</small></div></button></div><Botanical/><div className="side-footer">Thoughtfully guided.<br/>Grounded in your observations.</div></aside><main>
 {error&&<div className="notice error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button>{session&&<button onClick={()=>resume(session.id)}>Refresh session</button>}</div>}
 {!session?<><div className="page-heading"><div><div className="eyebrow">WELCOME TO ASDWISE</div><h1>Let’s talk about your child.</h1><p>A guided conversation about communication, play, and everyday life.</p></div><span className="age-tag">16–30 months</span></div><div className="content-grid"><form className="question-card onboarding" onSubmit={start}><h2>Start with a little context.</h2><p>The AI screening guide helps you record observations. A qualified professional makes diagnostic decisions.</p><fieldset><legend>Choose your experience</legend><div className="choices"><button type="button" disabled={!health?.live_available} className={mode==='interactive'?'chosen':''} onClick={()=>setMode('interactive')}>Caregiver interview</button><button type="button" className={mode==='simulation'?'chosen':''} onClick={()=>setMode('simulation')}>Synthetic demo</button></div></fieldset>
 {mode==='interactive'?<><label>Child’s preferred name<input name="name" maxLength={80} required placeholder="First name or nickname"/></label><div className="form-row"><label>Age in months<input name="age" type="number" min="16" max="30" required defaultValue={24}/></label><label>Your relationship<input name="relationship" required maxLength={60} defaultValue="Parent"/></label></div></>:<><div className="notice">Synthetic examples only. This mode uses stored fictional profiles and an offline report template, not live AI clinical analysis.</div><label>Example profile<select name="profile"><option value="moderate_likelihood">Liam · moderate-likelihood profile</option><option value="low_likelihood">Low-likelihood profile</option><option value="high_likelihood">High-likelihood profile</option></select></label></>}
 {!health?.live_available&&<p className="muted-copy">Live conversations and audio are waiting for a server-side API key. You can explore the complete flow with a synthetic profile.</p>}
 <label className="consent"><input type="checkbox" name="consent" required/><span>I understand this is a research screening tool, not a diagnosis. In live mode, my interview and any recorded audio are sent to OpenAI. This pilot stores encrypted interviews locally for up to seven days; I can delete them. Raw recordings are not retained by this app.</span></label><button className="primary" disabled={busy||!health}>{busy?'Starting…':mode==='simulation'?'Explore synthetic demo →':'Start conversation →'}</button>
 </form><aside className="support"><div className="support-art"><Botanical/></div><div className="eyebrow">A NOTE FOR YOU</div><h3>There’s no perfect answer.</h3><p>Think about what usually happens. You can describe an example, say you’re unsure, or pause along the way.</p><hr/><h4>Your words matter.</h4><p>Review every answer before it contributes to a screening report.</p></aside></div>{saved.length>0&&<section className="saved-sessions"><h2>Continue a recent interview</h2>{saved.map(s=><button className="saved-row" key={s.id} onClick={()=>resume(s.id)}><strong>{s.child.name}</strong><span>{s.mode==='simulation'?'Synthetic demo':'Caregiver'} · {s.status}</span><span>Continue →</span></button>)}</section>}</>
 :<>{session.mode==='simulation'&&<div className="demo-banner">SYNTHETIC DEMONSTRATION · Fictional profile · No live clinical assessment</div>}
 {view==='report'&&report?<Report report={report} session={session} onBack={()=>setView('review')}/>:view==='review'?<section className="review"><div className="eyebrow">YOUR RESPONSES</div><h1>A moment to review.</h1><p>Confirm your answers and add any context you’d like your care team to know.</p><div className="review-stats"><span><strong>{answered}</strong> / 20 recorded</span><span><strong>{session.score.missing.length}</strong> unresolved</span></div>
 <div className="table-scroll"><table><thead><tr><th>Question</th><th>Confirmed answer</th></tr></thead><tbody>{session.score.items.map(q=><tr key={q.id}><td>{q.id}. {q.label}</td><td>{session.answers[q.id]?<select aria-label={`Answer to ${q.label}`} value={session.answers[q.id].value} disabled={busy||['paused','stopped'].includes(session.status)} onChange={e=>mutate(`/answers/${q.id}`,{value:e.target.value},'PATCH')}><option value="yes">Yes</option><option value="no">No</option><option value="unknown">Not sure</option></select>:<span>Not answered</span>}</td></tr>)}</tbody></table></div>
 <section className="criterion"><h2>Anything else you’ve noticed?</h2><p>These optional observations add context; they do not change the 20-item score.</p>{[['onset','When did you first notice these patterns?'],['impact','How do they affect daily life, and in which settings?'],['routines','What happens when routines or plans change?'],['interests','Are any interests unusually intense or difficult to shift from?']].map(([k,label])=><label key={k}>{label}<textarea maxLength={2000} value={context[k]} onChange={e=>setContext({...context,[k]:e.target.value})}/></label>)}<button className="secondary" disabled={busy} onClick={()=>mutate('/context',context,'PATCH')}>Save additional context</button></section>
 <div className="report-actions"><button className="secondary" onClick={()=>setView('interview')}>← Return to interview</button><button className="primary" disabled={busy||session.status!=='complete'||session.report_status==='generating'||JSON.stringify(context)!==JSON.stringify(session.context)} onClick={()=>mutate('/reports')}>{session.report_status==='generating'?'Preparing report…':'Generate report →'}</button></div>{JSON.stringify(context)!==JSON.stringify(session.context)&&<p className="muted-copy">Save your additional context before generating.</p>}{session.status!=='complete'&&<p>Finish the interview to generate a report. Uncertain answers remain explicitly unresolved.</p>}
 {session.report_status==='generating'&&<div className="notice" role="status">Preparing the report and checking its evidence. You can return to this session if you close the page.</div>}{session.report_error&&<div className="notice error" role="alert">{session.report_error}</div>}
 {session.reports.length>0&&<section className="saved-sessions"><h2>Your reports</h2>{[...session.reports].reverse().map(r=><button className="saved-row" key={r.id} onClick={()=>openReport(r.id)}><span>{new Date(r.created).toLocaleString()}</span><span>{r.revision===session.revision?'Current':'Earlier responses'}</span><strong>Open report →</strong></button>)}</section>}
 </section>:<><div className="page-heading"><div><div className="eyebrow">{session.child.name.toUpperCase()}’S INTERVIEW</div><h1>One question at a time.</h1><p>Share what you’ve noticed, in your own words.</p></div><span className="age-tag">{session.child.age} months</span></div><div className="session-controls"><button className="secondary" disabled={busy||session.status==='complete'} onClick={()=>{setAuto(false);mutate('/control',{action:session.status==='running'?'pause':'resume'})}}>{session.status==='running'?'Pause interview':'Resume interview'}</button>{session.mode==='simulation'&&<><button className="secondary" disabled={busy||session.status!=='running'} onClick={()=>mutate('/control',{action:'step'})}>Next demo turn</button><button className="secondary" disabled={session.status!=='running'} onClick={()=>setAuto(!auto)}>{auto?'Stop automatic turns':'Run automatically'}</button></>}<button className="quiet" disabled={busy} onClick={()=>{if(window.confirm('Reset this interview? Existing reports will remain as earlier versions.')){setAuto(false);setContext({onset:'',impact:'',routines:'',interests:''});mutate('/control',{action:'reset'})}}}>Reset</button></div>
 {session.status==='complete'?<div className="question-card"><h2>Thank you for sharing.</h2><p>All 20 questions have a recorded response. Review anything you were unsure about before generating your report.</p><button className="primary" onClick={()=>{setAuto(false);setView('review')}}>Review responses →</button></div>:<section className="question-card conversation-card"><div className="question-meta"><span>QUESTION {String(session.current_question.id).padStart(2,'0')} / 20</span><span>{session.status==='running'?'In progress':session.status}</span></div><div className="progress" role="progressbar" aria-label="Screening progress" aria-valuenow={answered} aria-valuemin={0} aria-valuemax={20}><i style={{width:`${answered*5}%`}}/></div><div className="guide"><Mark/><span>ASDwise AI screening guide<small>Simulated Therapist Agent</small></span></div><h2>{session.current_question.text}</h2>
 <div className="transcript" aria-live="polite">{session.turns.filter(t=>t.question_id===session.current_question.id&&t.text!==session.current_question.text).map(t=><div key={t.id} className={`message ${t.role}`}><small>{t.role==='caregiver'?'Caregiver':'AI guide'}</small><p>{t.text}</p></div>)}</div>
 {session.status!=='running'?<div className="notice">The interview is paused. Resume whenever you’re ready.</div>:<>{session.pending?<div className="confirmation"><h3>How should we record your answer?</h3><p>Confirm the response that fits best. Choosing “Not sure” keeps this item unresolved.</p><div className="choices">{[['yes','Yes'],['no','No'],['unknown','Not sure']].map(([v,label])=><button key={v} disabled={busy} onClick={()=>mutate(`/answers/${session.current_question.id}`,{value:v},'PATCH')}>{label}</button>)}</div>{session.pending.suggested!=='unknown'&&<small>The AI suggested {session.pending.suggested}; your confirmation determines the recorded answer.</small>}<form className="clarification-form" onSubmit={e=>{e.preventDefault();mutate('/turns',{text,modality:original?'voice':'text',original_transcript:original})}}><label htmlFor="clarification">Add an example or ask for clarification<textarea id="clarification" maxLength={6000} value={text} onChange={e=>setText(e.target.value)} placeholder="Tell me a little more…"/></label><button className="secondary" disabled={busy||!text.trim()}>{busy?'Responding…':'Send clarification'}</button></form><VoiceControls session={session} enabled={health?.audio_available} disabled={busy||session.status!=='running'} onTranscript={v=>{setOriginal(v);setText(v)}} onError={setError}/><button className="help-link" onClick={()=>setHelp(!help)}>Help me decide</button>{help&&<p>Think about several recent situations. If neither answer fits or you need more context, keep this item marked “Not sure” and discuss it with your care team.</p>}</div>:<><form onSubmit={e=>{e.preventDefault();mutate('/turns',{text,modality:original?'voice':'text',original_transcript:original})}}><label htmlFor="response">Your response<textarea id="response" required maxLength={6000} value={text} onChange={e=>setText(e.target.value)} placeholder="Tell me about an everyday example…" disabled={busy}/></label>{original&&<p className="muted-copy">Voice transcript ready. Check the wording before sending.</p>}<div className="question-footer"><span>Your answer is not scored until you confirm it.</span><button className="primary" disabled={busy||!text.trim()}>{busy?'Guide is responding…':'Send response →'}</button></div></form><VoiceControls session={session} enabled={health?.audio_available} disabled={busy||session.status!=='running'} onTranscript={v=>{setOriginal(v);setText(v)}} onError={setError}/><div className="quick-answers"><span>Or record a short answer:</span>{[['yes','Yes'],['no','No'],['unknown','Not sure']].map(([v,label])=><button className="secondary" key={v} disabled={busy} onClick={()=>mutate(`/answers/${session.current_question.id}`,{value:v},'PATCH')}>{label}</button>)}</div></>}</>}
 </section>}
 <details className="history"><summary>Full interview transcript ({session.turns.filter(t=>t.role!=='superseded').length} messages)</summary>{session.turns.filter(t=>t.role!=='superseded').map(t=><div key={t.id} className={`message ${t.role}`}><small>{t.role==='caregiver'?'Caregiver':'AI guide'}{t.question_id?` · Q${t.question_id}`:''}</small><p>{t.text}</p></div>)}</details></>}
 <div className="session-bottom"><small>Encrypted local session · Automatically expires after seven days without activity</small><button className="danger-link" disabled={busy} onClick={remove}>Delete interview & reports</button></div></>}
 </main></div><footer className="app-footer"><span>ASDwise · Caregiver-centered understanding</span><span>Research pilot · Screening is not diagnosis</span></footer></div></div>
}
