'use client';
import {useState} from 'react';
import {sessionFetch} from '../session-client.mjs';
export default function Report({report,session,onBack}) {
 const [downloadError,setDownloadError]=useState(''),[downloading,setDownloading]=useState(false);
 async function download(){setDownloading(true);setDownloadError('');try{
  const response=await sessionFetch(`/sessions/${session.id}/reports/${report.id}/pdf`);
  if(!response.ok){const data=await response.json();throw Error(data.detail||'Download failed.');}
  const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='ASDWise-screening-report.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }catch(e){setDownloadError(e.message)}finally{setDownloading(false)}}
 const stale=report.revision!==session.revision;
 return <section className="report detailed-report"><div className="eyebrow">CAREGIVER SCREENING REPORT</div><h1>A clearer picture.<br/>A thoughtful next step.</h1><p>{report.child.name} · {report.child.age} months · {new Date(report.created).toLocaleDateString()}</p>
 {stale&&<div className="notice" role="alert">Your responses have changed. Generate an updated report before downloading.</div>}
 <div className="report-actions"><button className="secondary" onClick={onBack}>← Review responses</button>{!stale&&<button className="primary" disabled={downloading} onClick={download}>{downloading?'Downloading…':'Download PDF ↓'}</button>}</div>
 {downloadError&&<p role="alert">{downloadError}</p>}
 <details className="criterion observation-scope"><summary>About these observations · {report.child.relationship||'Caregiver'}{report.observation_context?.setting?` · ${report.observation_context.setting}`:''}</summary><h2>Whose observations are included</h2><p><strong>Caregiver:</strong> {report.child.relationship||'Not specified'}</p>{[['setting','Setting'],['frequency','Frequency / times'],['familiarity','Time caring for the child']].map(([key,label])=><p key={key}><strong>{label}:</strong> {report.observation_context?.[key]||'Not specified'}</p>)}<p>This report reflects one caregiver’s account. Different settings can bring different observations.</p></details>
 <nav className="report-jump" aria-label="Report sections"><a href="#score">Screening</a><a href="#summary">What you shared</a><a href="#observations">Supporting detail</a><a href="#recommendations">Next steps</a></nav>
 <div className="report-banner" id="score"><div className="stat"><strong>{report.score.total??'—'}<small> / 20</small></strong></div><div><h3>{report.score.band==='INCOMPLETE'?'Responses need review':`${report.score.band.toLowerCase()} likelihood · initial screen`}</h3><p>Formal Follow-Up: {report.score.followup}</p></div></div><p>{report.score.recommendation}</p>
 <article className="criterion" id="summary"><h2>What you shared</h2><p>{report.analysis.summary}</p>{report.analysis.strengths.length>0&&<><h3>Reported strengths</h3><ul>{report.analysis.strengths.map((s,i)=><li key={i}>{s}</li>)}</ul></>}<h3>Your next step</h3><p>{report.recommendations['Primary recommendation']}</p><p>{report.disclaimer}</p></article>
 {report.context.other_observations&&<article className="criterion"><h2>Different caregiver perspectives</h2><p>{report.context.other_observations}</p><p className="muted-copy">Recorded as this caregiver’s account of other observations. The screening does not choose one account over another or assume the same behavior in every setting.</p></article>}
 <details className="criterion"><summary>Review all 20 answers</summary><h2>All 20 responses</h2><div className="table-scroll"><table><thead><tr><th>#</th><th>Item</th><th>Answer</th><th>Result</th></tr></thead><tbody>{report.score.items.map(q=><tr key={q.id}><td>{q.id}</td><td>{q.label}</td><td>{q.answer}</td><td><span className={`status-chip ${q.result==='elevated likelihood'?'concern':''}`}>{q.result}</span></td></tr>)}</tbody></table></div></details>
 <details className="criterion technical-observations" id="observations"><summary>Supporting detail: DSM-5-informed observations</summary><h2>DSM-5-informed observations</h2><p className="muted-copy">Observations from this interview do not establish diagnostic criteria. Missing evidence remains explicitly uncertain.</p>
 {report.analysis.criteria.map(c=><article className="criterion" key={c.code}><div className="criterion-heading"><h3>{c.code} · {c.title}</h3><span className={`status-chip ${c.status==='reported concern'?'concern':''}`}>{c.status}</span></div><p>{c.interpretation}</p><details><summary>Evidence from the interview ({c.evidence.length})</summary>{c.evidence.length?c.evidence.map((e,i)=><div className="evidence-quote" key={i}><strong>{e.question_id?`Q${e.question_id}`:'Supplemental context'} · Caregiver observation</strong><blockquote>“{e.quote}”</blockquote><p><strong>Interpretation:</strong> {e.interpretation}</p><small>Transcript reference: {e.turn_id.slice(0,8)}</small></div>):<p>No sufficient caregiver evidence was recorded for this criterion.</p>}</details><p><strong>Missing context:</strong> {c.missing_context}</p><small>Reference: Carpenter, February 2013, pages {c.source_pages.join(', ')}.</small></article>)}</details>
 <article className="criterion" id="assessment"><h3>Additional diagnostic context</h3>{Object.entries(report.context).filter(([k])=>k!=='other_observations').map(([k,v])=><p key={k}><strong className="capitalize">{k}:</strong> {v||'Not reported'}</p>)}<p>Onset, functional impact, and alternative explanations require professional assessment. No diagnosis or support-severity level is assigned here.</p></article>
 <article className="criterion" id="recommendations"><h2>Recommendations</h2>{Object.entries(report.recommendations).map(([k,v])=><section key={k}><h3>{k}</h3><p>{v}</p></section>)}</article>
 <article className="criterion"><h2>Limitations & references</h2><p>{report.disclaimer}</p><ul>{report.analysis.limitations.map((x,i)=><li key={i}>{x}</li>)}</ul>{report.references.map((r,i)=><p key={i}>{r.url?<a href={r.url} target="_blank" rel="noreferrer">{r.title} ↗</a>:<>{r.title} · {r.author} · {r.date}<br/><small>{r.status}</small></>}</p>)}<small>Report {report.id.slice(0,8)} · revision {report.revision} · {report.model} · {report.prompt_version}</small></article>
 </section>
}
